version: '3.8'
services:
  app:
    build:
      context: .
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_NAME=orders_db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: orders_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
