// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID           string  `json:"id"`
	CustomerName string  `json:"customerName"`
	TotalAmount  float64 `json:"totalAmount"`
	CreatedAt    string  `json:"createdAt"`
}

type Query struct {
}
